version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test1:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "testing stuff"
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "hellllooooo!"
workflows:
  version: 2
  build_test1_and_lint:
    jobs:
      - build
      - hithere
      - test1:
          requires:
            - hithere

